---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.12.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci
  docker:
    image: plugins/docker
    repo: $$DRONE_REPO_OWNER/net
    tags:
      - $$DRONE_TAG
    when:
      event: tag
