---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.12.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci
  docker_push:
    image: rancher/dapper:1.12.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -lR
    - sh scripts/docker_push
    when:
      event: tag
