---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.12.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci
  docker:
    image: rancher/dapper:1.12.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - pwd
    - sh -x /go/src/github.com/rancher/rancher-net/scripts/docker_push
    when:
      event: tag
